// client-angular/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import {Store} from "@ngrx/store";
import {getWorks, setInfo} from "../../store/app.actions";

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent  {
}

<div class="navbar">
  <div class="navbar__container">
    MERNPortfolio
    <button class="navbar__container__admin-btn">
      Админка
    </button>
  </div>
</div>

// client/src/components/navbar/navbar.tsx
import * as React from "react";
import { useDispatch } from "react-redux";
import { ReduxActionTypes } from "../../types/redux";
import "./navbar.scss";

const Navbar = () => {
  const dispatch = useDispatch();
  const authHandler = () => {
    dispatch({ type: ReduxActionTypes.IS_AUTH_MODAL });
  };

  return (
    <div className="navbar">
      <div className="navbar__container">
        MERNPortfolio
        <button className="navbar__container__admin-btn" onClick={authHandler}>
          Админка
        </button>
      </div>
    </div>
  );
};

export default Navbar;
